# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bdd_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(default=' ', max_length=400)),
                ('prenom', models.CharField(default=' ', max_length=400)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('titre', models.CharField(default=' ', max_length=400)),
                ('adresse', models.CharField(default=' ', max_length=400)),
                ('complement_adresse', models.CharField(blank=True, max_length=400)),
                ('code_postal', models.CharField(default=' ', max_length=400)),
                ('ville', models.CharField(default=' ', max_length=400)),
                ('telephone', models.CharField(default=' ', max_length=400)),
                ('email', models.CharField(default=' ', max_length=400)),
                ('code_parrainage', models.CharField(default=' ', max_length=400)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='bdd_devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(default=' ', max_length=400)),
                ('prenom', models.CharField(default=' ', max_length=400)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('titre', models.CharField(default=' ', max_length=400)),
                ('adresse', models.CharField(default=' ', max_length=400)),
                ('complement_adresse', models.CharField(blank=True, max_length=400)),
                ('code_postal', models.CharField(default=' ', max_length=400)),
                ('ville', models.CharField(default=' ', max_length=400)),
                ('telephone', models.CharField(default=' ', max_length=400)),
                ('email', models.CharField(default=' ', max_length=400)),
                ('date_de_demande', models.DateTimeField(auto_now_add=True)),
                ('sujet', models.CharField(default=' ', max_length=400)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Devis demande',
                'ordering': ['date_de_demande'],
            },
        ),
        migrations.CreateModel(
            name='bdd_postes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_du_poste', models.CharField(default=' ', max_length=400)),
                ('description_poste', models.CharField(default=' ', max_length=5000)),
                ('lieu_du_poste', models.CharField(default=' ', max_length=400)),
                ('domaine_activite', models.CharField(default=' ', max_length=400)),
                ('type_emploi', models.CharField(default=' ', max_length=400)),
                ('horaire_travail', models.CharField(default=' ', max_length=400)),
                ('date_de_publication', models.DateField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Poste',
                'ordering': ['date_de_publication'],
            },
        ),
        migrations.CreateModel(
            name='bdd_postes_demandeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_du_poste', models.CharField(default=' ', max_length=400)),
                ('telephone', models.CharField(default=' ', max_length=400)),
                ('email', models.CharField(default=' ', max_length=400)),
                ('date_de_demande', models.DateField(auto_now_add=True)),
                ('cv', models.FileField(upload_to='cv_demande/')),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Poste demandeur',
                'ordering': ['date_de_demande'],
            },
        ),
    ]
