# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd_postes',
            name='description_poste',
            field=models.TextField(default=' '),
        ),
    ]
