# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_auto_20191204_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='bdd_assistance_technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(choices=[('Pompe_a_chaleur', 'Pompe_a_chaleur'), ('Isolation', 'Isolation'), ('Domotique', 'Domotique'), ('Chaudiere', 'Chaudiere'), ('Ballon_thermodynamique', 'Ballon_thermodynamique')], max_length=50, null=True)),
                ('titre_du_probleme', models.CharField(default=' ', max_length=400)),
                ('description_du_probleme', models.TextField(default=' ')),
                ('url_video_youtube', models.CharField(default=' ', max_length=400)),
            ],
        ),
    ]
