# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_bdd_assistance_technique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdd_assistance_technique',
            options={'ordering': ['equipement'], 'verbose_name': 'Assistance technique'},
        ),
        migrations.AddField(
            model_name='bdd_assistance_technique',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
