# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_auto_20191204_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd_assistance_technique',
            name='solution_du_probleme',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='bdd_assistance_technique',
            name='url_video_youtube',
            field=models.CharField(default=' ', max_length=400, null=True),
        ),
    ]
