# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_auto_20191204_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd_assistance_technique',
            name='solution_du_probleme',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='bdd_assistance_technique',
            name='url_video_youtube',
            field=models.CharField(blank=True, default=' ', max_length=400),
        ),
    ]
