# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_auto_20191204_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='bdd_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(choices=[('Pompe_a_chaleur', 'Pompe à chaleur'), ('Isolation', 'Isolation'), ('Domotique', 'Domotique'), ('Chaudiere', 'Chaudiere'), ('Ballon_thermodynamique', 'Ballon thermodynamique')], max_length=50, null=True)),
                ('marque_du_produit', models.CharField(default=' ', max_length=50)),
                ('titre_du_produit', models.CharField(default=' ', max_length=50)),
                ('image_du_produit', models.ImageField(upload_to='image_produit/')),
                ('premiere_phrases_accroche', models.CharField(default=' ', max_length=100)),
                ('deuxieme_phrases_accroche', models.CharField(default=' ', max_length=100)),
                ('description_detaille_produit', models.TextField(default=' ')),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['equipement'],
            },
        ),
    ]
