# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-04 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_bdd_produit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdd_produit',
            options={'ordering': ['equipement', 'titre_du_produit'], 'verbose_name': 'Produit'},
        ),
    ]
